### ISSUE TITLE
Fail to install ridge in R4.0.2 in MacOS

### ISSUE THREAD

**Issue by xlucpu** [SteffenMoritz/ridge#14]
Hi, I kept getting error when installing ridge in the latest version of R4.0.2 in MacOS (fine in Windows system).
Below is the error information:
![ff1987cbfb73477aeab700db091df28](https://user-images.githubusercontent.com/57204704/93729453-179ed300-fbf7-11ea-95a2-d4a1dcbf00bc.jpg)
Any solutions?
Many thanks advanced!

**Comment by SteffenMoritz** [comment]
Hello Xiaofan Lu, thanks a lot for this report.

I actually already suspected that this might fail for some Mac users, because the CRAN check page ( https://cran.r-project.org/web/checks/check_results_ridge.html ) shows an error for the release mac version. But till know I wasn't really able to fix the problem, because I could not replicate it (tried on several Macs and it always just installed fine).

Could you maybe give me more information about your settings, then I can try to replicate the problem and maybe solve it.

R Version you said is  R4.0.2
What is your Mac OS Version? (mine is 10.15.3)

Please also run this in the **Mac OS Terminal** and make 100% sure lib gsl is installed (and try installation again afterwards)

`brew install gsl
`

Afterwards would be nice if you could post the **Mac OS Terminal** output of

`which gsl-config`

**Comment by xlucpu** [comment]
> Hello Xiaofan Lu, thanks a lot for this report.
> 
> I actually already suspected that this might fail for some Mac users, because the CRAN check page ( https://cran.r-project.org/web/checks/check_results_ridge.html ) shows an error for the release mac version. But till know I wasn't really able to fix the problem, because I could not replicate it (tried on several Macs and it always just installed fine).
> 
> Could you maybe give me more information about your settings, then I can try to replicate the problem and maybe solve it.
> 
> R Version you said is R4.0.2
> What is your Mac OS Version? (mine is 10.15.3)
> 
> Please also run this in the **Mac OS Terminal** and make 100% sure lib gsl is installed (and try installation again afterwards)
> 
> `brew install gsl `
> 
> Afterwards would be nice if you could post the **Mac OS Terminal** output of
> 
> `which gsl-config`

Many thanks for your timely reply. I have successfully installed ridge after correct installation of gsl in MacOS Catalina 10.15.6.

**Comment by SteffenMoritz** [comment]
Oh, that sounds great! Perfect, thanks for the report. Might be an indicator, that on the CRAN Mac OS Status Server ( https://cran.r-project.org/web/checks/check_results_ridge.html )  lib gsl is also just not installed.
